-- 코드를 입력하세요
SELECT 
    BK.AUTHOR_ID,
    AR.AUTHOR_NAME,
    BK.CATEGORY,
    SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK BK
INNER JOIN AUTHOR AR ON BK.AUTHOR_ID = AR.AUTHOR_ID
INNER JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') ='202201'
GROUP BY BK.AUTHOR_ID, AR.AUTHOR_NAME, BK.CATEGORY
ORDER BY BK.AUTHOR_ID ASC, BK.CATEGORY DESC