-- 코드를 입력하세요
SELECT  
        RESULT.REST_ID,
        RESULT.REST_NAME,
        RESULT.FOOD_TYPE,
        RESULT.FAVORITES,
        RESULT.ADDRESS,
        RESULT.SCORE
    FROM
(
    SELECT
        RI.REST_ID,
        RI.REST_NAME,
        RI.FOOD_TYPE,
        RI.FAVORITES,
        RI.ADDRESS,
        ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE,
        RI.VIEWS
    FROM REST_INFO RI
    INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
        WHERE RI.ADDRESS LIKE '서울%'
    GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, RI.VIEWS
) RESULT
ORDER BY RESULT.SCORE DESC, RESULT.VIEWS DESC