-- 코드를 입력하세요
SELECT  
    RESULT.FLAVOR
FROM(
SELECT 
       SUM(FH.TOTAL_ORDER + JY.TOTAL_ORDER) AS TOTAL,
       FH.FLAVOR
FROM FIRST_HALF FH 
    INNER JOIN  JULY JY ON JY.FLAVOR = FH.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY SUM(FH.TOTAL_ORDER + JY.TOTAL_ORDER) DESC
) RESULT
WHERE ROWNUM <= 3
