-- 코드를 입력하세요
SELECT
    UGU.USER_ID AS USER_ID,
    UGU.NICKNAME AS NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC