-- 코드를 입력하세요
SELECT CATEGORY
,   SUM(SALES) AS TOTAL_SALES
FROM BOOK BK 
INNER JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
WHERE EXTRACT(MONTH FROM SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC