-- 코드를 입력하세요
SELECT
    BK.BOOK_ID,
    AR.AUTHOR_NAME,
    TO_CHAR(BK.PUBLISHED_DATE, 'YYYY-MM-DD')
FROM BOOK BK
    INNER JOIN AUTHOR AR ON BK.AUTHOR_ID = AR.AUTHOR_ID
WHERE BK.CATEGORY IN ('경제')
ORDER BY PUBLISHED_DATE ASC